---
spring:
  datasource:
    url: jdbc:mariadb://172.17.0.2:3306/local-db

---

spring:
  profiles: docker
  datasource:
      url: jdbc:mariadb://192.168.100.101:3306/local-db
  jpa:
    hibernate:
      ddl-auto: update
---